output_folder: /work/kevin8ntust/output

data: 
  image_size: -1  # If image_size == -1, don't resize the image
  crop_size: -1  # The size for the random crop
  max_data_per_epoch: -1
  name_filter_domainA: '*jpg'
  name_filter_domainB: '*jpg'
  domainA_path: ../data/satellite/maps/trainA
  domainB_path: ../data/satellite/maps/trainB

train:
  lr: 0.0002
  device: cuda
  batch_size: 1
  total_epochs: 200
  start_reduce_lr_epoch: 100
  model_description: Satellite
  save_freq: 1
  lambda:
    identity: -1 # 5.0 (If identity is set to -1, loss_G_total will not including identity loss)
    cycle: 10.0

val:
  device: cuda
  num_visualization_img: 100 # If num_visualization_img == -1, use all data to do visualization
  data:
    image_size: -1  # If image_size == -1, don't resize the image
    crop_size: -1  # The size for the random crop
    name_filter_domainA: '*jpg'
    name_filter_domainB: '*jpg'
    domainA_path: ../data/satellite/maps/valA
    domainB_path: ../data/satellite/maps/valB
# /home/kevin8ntust/deepLearning/CycleGAN
model:
  use_variant: false
  num_hourglass: 8  # At most 8